server
{
    listen 8081;
    server_name localhost;

    root ./www;
    index index.html;

    # client_max_body_size 200000;

    error_page 400 ./www/errors/400.html;
    error_page 403 ./www/errors/403.html;
    error_page 404 ./www/errors/404.html;
    error_page 405 ./www/errors/405.html;
    error_page 413 ./www/errors/413.html;
    error_page 500 ./www/errors/500.html;

    location /
    {
        methods GET;
        autoindex off;
    }

    location /errors
    {
        root ./www/errors;
        methods GET;
        autoindex on;
    }

    location /static
    {
        root ./www/static;
        methods GET;
        autoindex off;
    }

    location /upload
    {
        root ./uploads;
        autoindex on;
    }

    location /signup {
        root ./cgi;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        cgi_script signup.py;
    }

    location /login {
        root ./cgi;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        cgi_script login.py;
    }

    location /cgi
    {
        root ./cgi;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        cgi_script run_c.py;    
    }

    location /go-google
    {
        return 301 https://youtube.com;
    }
}


server 
{
    listen 8082;
    server_name localhost;

    root ./www;
    index index.html;


    error_page 400 ./www/errors/400.html;
    error_page 403 ./www/errors/403.html;
    error_page 404 ./www/errors/404.html;
    error_page 405 ./www/errors/405.html;
    error_page 413 ./www/errors/413.html;
    error_page 500 ./www/errors/500.html;

    location /
    {
        methods GET;
        autoindex off;
    }

    location /errors
    {
        root ./www/errors;
        methods GET;
        autoindex off;
    }

    location /static
    {
        root ./assets;
        methods GET;
        autoindex off;
    }
}